apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: local-apiserversource
spec:
  serviceAccountName: demo-serviceaccount
  mode: Resource
  resources:
#    - apiVersion: serving.knative.dev/v1
#      kind: Service
    - apiVersion: v1
      kind: Pod
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: multus-ifaces-annotator
---