---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewall
  namespace: default
  labels:
    multus-app: firewall
    istio-injection: disabled
spec:
  selector:
    matchLabels:
      multus-app: firewall
  replicas: 2
  template:
    metadata:
      labels:
        multus-app: firewall
        istio-injection: disabled
      annotations:
        k8s.v1.cni.cncf.io/networks: default/lb-fw-macvlan-conf, default/fw-sv-macvlan-conf
    spec:
      containers:
        - name: firewall-sample
          image: amit235/ubuntu-ufw
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command: ['/bin/sh', '-c', 'sleep infinity']
