apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: default
  labels:
    multus-app: server
spec:
  selector:
    matchLabels:
      multus-app: server
  replicas: 1
  template:
    metadata:
      labels:
        multus-app: server
      annotations:
        k8s.v1.cni.cncf.io/networks: default/fw-sv-macvlan-conf
    spec:
      containers:
        - name: node-server
          image: fvalente95/nginx-server:0.3
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
          - containerPort: 5000
            name: server
            protocol: TCP

